
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
   builder: html
   configuration: python/docs/conf.py

python:
   install:
   - requirements: requirements-torch.txt
   - requirements: requirements-doc.txt
   - method: pip
     path: python

formats:
  - epub
  - pdf
